FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

COPY uv.lock pyproject.toml ./
RUN --mount=type=cache,target=/root/.cache/uv \ 
    uv sync --no-install-project --no-dev

COPY deployment-project/data/model/lr_pipeline.joblib data/model/lr_pipeline.joblib

COPY deployment-project/app.py . 
RUN --mount=type=cache,target=/root/.cache/uv \ 
    uv sync --frozen --no-dev

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000

ENTRYPOINT ["uvicorn"]

CMD ["app:app", "--host", "0.0.0.0", "--port", "8000"]